Adding workflow for pushing container to github packages
wtsi-npg/containers pull request #14
Opened 2021-04-15 15:39 UTC by FredDodd6

Adding GitHub Action workflow to push images to GitHub Packages.
change tag namespace to include ghcr.io

2021-04-21 12:11 UTC, kjsanger requested changes

2021-04-21 12:11 UTC, kjsanger commented on docker/Makefile
> +
Please remove the extra whitespace changes.

2021-05-27 10:43 UTC, kjsanger commented
Is this still in play, @FredDodd6 , @dkj ?

2021-05-27 11:23 UTC, dkj commented
> Is this still in play, @FredDodd6 , @dkj ?

I think it gives us an extra path with one less component (DockerHub) - so only a good thing? The last problem I was aware of was flaky connections to pick up official iRODS pacakges...

2021-05-27 12:39 UTC, kjsanger commented
I'll leave open. I was asking because ~1 month since last activity.

2021-06-07 17:42 UTC, dkj commented on docker/Makefile
> +TAG_NAMESPACE=ghcr.io/$(REPO_OWNER)
How about 
```suggestion
ifdef REPO_OWNER
TAG_NAMESPACE?=ghcr.io/$(REPO_OWNER)
else
TAG_NAMESPACE?=wsinpg
endif
```
allow us to run with a `TAG_NAMESPACE` suitable for DockerHub, or of choice with `make TAG_NAMESPACE=foo all`

2021-06-09 18:11 UTC, dkj commented on .github/workflows/pushing_container_image.yml
> +            docker push ghcr.io/${{ env.REPO_OWNER }}/ub-12.04-conda:$TAG
```suggestion
            docker push ghcr.io/${{ env.REPO_OWNER }}/ub-16.04-base:$TAG
            docker push ghcr.io/${{ env.REPO_OWNER }}/ub-18.04-base:$TAG
            docker push ghcr.io/${{ env.REPO_OWNER }}/ub-16.04-conda:$TAG
```
Update following removal of Precise (12.04) #15

2021-06-09 19:04 UTC, merged